replicaCount: 1
image:
  repository: peishu/productcatalogservice
  tag: 0902c8b928e48fab8e28140bd688749244aefa56
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 3550
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
